-- SQL Drill — "rows above their group's average" (2026-06-24)
-- ============================================================
-- Classic MLE/DS SQL pattern (joins + aggregation + GROUP BY).
--
-- TABLE: employees
--   emp_id | name    | dept     | salary
--   -------+---------+----------+-------
--     1    | Asha    | ML       | 150
--     2    | Ben     | ML       | 120
--     3    | Chen    | ML       | 200
--     4    | Dev     | Data     |  90
--     5    | Eve     | Data     | 110
--     6    | Fay     | Data     | 100
--     7    | Gus     | Infra    | 130
--
-- TASK: Find all employees who earn MORE than the AVERAGE salary of THEIR
--       OWN department. Return: name, dept, salary.
--
-- Dept averages: ML = (150+120+200)/3 = 156.67  |  Data = 100  |  Infra = 130
-- Expected:
--   name | dept | salary
--   -----+------+-------
--   Chen | ML   | 200      (200 > 156.67)
--   Eve  | Data | 110      (110 > 100)
--
-- ─────────────────────────────────────────────────────
-- Two ways to solve (both worth knowing — tell me which you'll use):
--   (a) Subquery/CTE: compute dept avgs, JOIN back, filter salary > avg.
--   (b) Window function: AVG(salary) OVER (PARTITION BY dept), then filter.
-- ─────────────────────────────────────────────────────

-- Your query here:

